FORMAT: 1A
HOST: http://xo-login.herokuapp.com/

# xo_login Api

xo_login is a simple API allowing consumers to login using their username and password.

# xo-login API Root [/]


## Login user [GET]

Request contains username and password and with this credentials
2 types of responses are returned:
1) Response 200, which is returned in case user is registered in the system 
   and response json contains token
2) Response 401, which is returned and indicates, that user is not registered.

+ username (string) - name of the user
+ password (string) - password of the user
+ token (string) - system unique token of the user

+ Request (application/json)

            {
                "username":"Anna",
                "password":"123qwe"
            }

+ Response 200 (application/json)

    + Body

            {
                "token":"7b5be1f4-78f9-4e32-8b75-a7e87afec329"
            }

+ Response 401 (application/json)

